version: '3.8'
services:
  auth_service:
    container_name: auth_service
    build: ./server/authentication-microservice
    command: npm run dev
    volumes:
      - ./server/authentication-microservice:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8080"
    links:
      - auth_mongo
    environment:
      - dev=1
      - db_service_name=auth_mongo
      - db_name=auth
      - db_username=admin
      - db_password=admin
      - db_retry_time=3000
      - jwt_secret=secret-jwt-key
  auth_mongo:
    container_name: auth_mongo
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service