# Generated by Django 3.2.3 on 2021-05-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=8)),
                ('symbol', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='gamelisting',
            old_name='negotiable',
            new_name='is_negotiable',
        ),
        migrations.AlterField(
            model_name='gamelisting',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='gamelisting',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listings_api.currency'),
        ),
        migrations.AddField(
            model_name='gamelisting',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listings_api.platform'),
        ),
    ]
