# Generated by Django 3.2.5 on 2021-07-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings_api', '0002_auto_20210514_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='short_name',
            new_name='code',
        ),
    ]
