# Generated by Django 3.2.6 on 2021-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_api', '0003_auto_20210705_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings-images'),
        ),
    ]
