# Generated by Django 3.2.6 on 2021-09-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gamelisting',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='gamelisting',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='image',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
        migrations.DeleteModel(
            name='GameListing',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='UserFavourite',
        ),
    ]
